spring.application.name=San
spring.datasource.url=jdbc:mysql://localhost:3306/jvmpro
spring.datasource.username = root
spring.datasource.password = San@2052006

#Hibernate Defination for auto create table structure

spring.jpa.hibernate.ddl-auto= create-drop